// -----------------------------------------------------------
//  File: global.h
//  Author: Gregory Rehbein
//
//  Copyright (C) 2012 Gregory Rehbein <gmrehbein@gmail.com>
// -----------------------------------------------------------

#pragma once

#include <string>
#include <vector>
#include <set>
#include <utility>
#include <boost/pool/singleton_pool.hpp>
#include "rectangle.h"

struct Global {
  static inline std::string inFile;
  static inline std::string outFile;
  static inline std::vector<std::vector<int>> field;
  static inline std::set<std::pair<int, int>> strawberries;

  //----------------------------------
  // Number of strawberries contained
  // within the rectangle determined by
  // the 4 coordinates.
  //-----------------------------------
  static size_t weightOfRectangle
  (int topLeftRow, int topLeftColumn, int bottomRightRow, int bottomRightColumn);

  static inline size_t numRows = 0;
  static inline size_t numColumns = 0;

  //--------------------------------------------------
  // All rectangles generated by the optimizer are
  // created using the Global::rectanglePool interface.
  // All memory for the rectangles is released at the end
  // of an optimization run.
  //--------------------------------------------------
  using tag_for_pool = struct {};
  static boost::singleton_pool< tag_for_pool, sizeof(Rectangle)> rectanglePool;
};
