// -----------------------------------------------------------
//  File: global.h
//  Author: Gregory Rehbein
//
//  Copyright (C) 2012 Gregory Rehbein <gmrehbein@gmail.com>
// -----------------------------------------------------------

#ifndef GLOBAL_H
#define GLOBAL_H

#include <string>
#include <vector>
#include <set>
#include <utility>
#include <boost/pool/singleton_pool.hpp>
#include <boost/utility.hpp>
#include "rectangle.h"

struct Global {
  static std::string inFile;
  static std::string outFile;
  static std::vector<std::vector<int> > field;
  static std::set<std::pair<int, int> > strawberries;

  //----------------------------------
  // Number of strawberries contained
  // within the rectangle determined by
  // the 4 coordinates.
  //-----------------------------------
  static size_t weightOfRectangle
  (int topLeftRow, int topLeftColumn, int bottomRightRow, int bottomRightColumn);

  static size_t numRows;
  static size_t numColumns;

  //--------------------------------------------------
  // All rectangles generated by the optimizer are
  // created using the Global::rectanglePool interface.
  // All memory for the rectangles is released at the end
  // of an optimization run.
  //--------------------------------------------------
  typedef struct {} tag_for_pool;
  static boost::singleton_pool< tag_for_pool, sizeof(Rectangle)> rectanglePool;
};

#endif
